DE45455 backport
Brightspace/brightspace-integration pull request #5102
Opened 2021-11-04 18:30 UTC by KaiPrince

## Overview

Backport the fix in https://github.com/BrightspaceHypermediaComponents/foundation-components/pull/340 to `20.21.11`.

### Reason for change

See ticket: [DE45455](https://rally1.rallydev.com/#/?detail=/defect/610442836939&fdp=true): Work To Do Widget > 20.21.9 > Widget items showing early due date after Daylight Savings Time (Nov 7)

Also, related slack thread: https://d2l.slack.com/archives/C02HQ2QDZLM/p1636042049216300?thread_ts=1635968795.201400&cid=C02HQ2QDZLM

### Changes summarized

- Update `package-lock` to point to the release commit: https://github.com/BrightspaceHypermediaComponents/foundation-components/commit/66d438ed4de146b49422230881665b3606728484

### Suggested future tasks

None.

## Checklist

- [ ] No new warnings are introduced
- [ ] Comments and documentation are up to date
- [ ] TODOs resolved or added to issue tracker
- [ ] No commented-out code
- [ ] This isn't a 'quick-and-dirty' job

2021-11-04 18:56 UTC, dmd2l commented on package-lock.json
> +      "version": "github:BrightspaceHypermediaComponents/foundation-components#66d438ed4de146b49422230881665b3606728484",
Is that backport url correct ( ie  https://github.com/BrightspaceHypermediaComponents/foundation-components/pull/340 ).  This code doesn't look the same :grimacing:

2021-11-04 18:59 UTC, klhuff commented on package-lock.json
> +      "version": "github:BrightspaceHypermediaComponents/foundation-components#66d438ed4de146b49422230881665b3606728484",
It looks like in this case, we're just pointing the 20.21.11 version of BSI to the new version of the component that was created based on my commit. I think this is fine, as long as there haven't been any other changes to the component.

2021-11-04 18:59 UTC, klhuff approved these changes

2021-11-04 19:00 UTC, dmd2l commented on package-lock.json
> +      "version": "github:BrightspaceHypermediaComponents/foundation-components#66d438ed4de146b49422230881665b3606728484",
I'm not really sure what I'm looking at here, but if @klhuff is happy that's good enough for me  :+1:

2021-11-04 19:00 UTC, dmd2l approved these changes

2021-11-04 19:01 UTC, grant-cleary commented on package-lock.json
> +      "version": "github:BrightspaceHypermediaComponents/foundation-components#66d438ed4de146b49422230881665b3606728484",
Yeah, it looks like this repo doesn't use maintenance branches so this is likely the way to go.

2021-11-04 19:01 UTC, grant-cleary submitted a review, later dismissed

2021-11-04 19:52 UTC, KaiPrince commented on package-lock.json
> +      "version": "github:BrightspaceHypermediaComponents/foundation-components#66d438ed4de146b49422230881665b3606728484",
I used the release commit: https://github.com/BrightspaceHypermediaComponents/foundation-components/releases/tag/v0.58.1

2021-11-04 20:08 UTC, bearfriend commented on package-lock.json
> +      "version": "github:BrightspaceHypermediaComponents/foundation-components#66d438ed4de146b49422230881665b3606728484",
A little uncomfortable with features going out that weren't meant for 20.21.11. That repo does actually use maintenance branches, it's just very rare. I cherry-picked the changes to a new branch. We can just update this this point at `23387ff01d13d17dbaea5ee0a297ec713cf93ef7` instead.

2021-11-04 20:10 UTC, grant-cleary commented on package-lock.json
> +      "version": "github:BrightspaceHypermediaComponents/foundation-components#66d438ed4de146b49422230881665b3606728484",
Ah okay. Admittedly I only checked the 20 or so most recent branches. If this release has unrelated changes to it, then yes, I would not merge this change.

2021-11-04 20:10 UTC, bearfriend commented on package-lock.json
> +      "version": "github:BrightspaceHypermediaComponents/foundation-components#66d438ed4de146b49422230881665b3606728484",
https://github.com/BrightspaceHypermediaComponents/foundation-components/tree/release/0.56.x

2021-11-04 21:05 UTC, bearfriend requested changes

2021-11-04 21:05 UTC, bearfriend commented on package-lock.json
> +      "version": "github:BrightspaceHypermediaComponents/foundation-components#66d438ed4de146b49422230881665b3606728484",
```suggestion
      "version": "github:BrightspaceHypermediaComponents/foundation-components#23387ff01d13d17dbaea5ee0a297ec713cf93ef7",
```

2021-11-05 14:52 UTC, grant-cleary approved these changes

2021-11-05 14:56 UTC, dmd2l approved these changes

2021-11-05 15:13 UTC, bearfriend approved these changes

2021-11-05 15:21 UTC, merged